# .github/workflows/ci-cd.yml

name: CI / CD Pipeline

on:
  workflow_dispatch:          # manual trigger
  push:
    branches: [ main ]        # on push to main
  pull_request:
    branches: [ main ]        # on PRs to main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true    # cancel in‑flight runs on the same ref

jobs:
  build-and-deploy:
    name: 🏗️ Build & Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      # 1️⃣ Checkout source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Java 21 & cache Maven deps
      - name: Set up JDK 21 and cache Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Cache Maven local repo
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # 3️⃣ Run tests (fail-fast)
      - name: Run tests
        run: mvn test --batch-mode

      # 4️⃣ Package JAR
      - name: Package application
        run: mvn package -DskipTests --batch-mode

      # 5️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6️⃣ Build & push Docker image
      - name: Build and push Docker image
        run: |
          IMAGE=yourdockerhubusername/your-image-name:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      # 7️⃣ Trigger Render deploy hook
      - name: Trigger Render redeploy
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
