# .github/workflows/ci-cd.yml

name: CI / CD Pipeline

# Allow manual runs + on push or PR to main
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Prevent overlapping runs on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Test & Package Job
  test-and-package:
    name: Test & Package
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_USERNAME: ${{ secrets.BOT_USERNAME }}
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run tests & package
        run: mvn clean package --batch-mode

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-jar
          path: target/*.jar

  # Docker Build & Push Job
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test-and-package
    environment: production
    steps:
      - name: Checkout code (for Dockerfile)
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: spring-boot-jar
          path: target/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build \
            -t yourdockerhubusername/your-image-name:latest \
            --file Dockerfile \
            .

      - name: Push Docker image
        run: |
          docker push yourdockerhubusername/your-image-name:latest

      - name: Trigger Render redeploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
